rosbag2_bagfile_information:
  compression_format: ''
  compression_mode: ''
  duration:
    nanoseconds: 155541897649
  message_count: 204302
  relative_file_paths:
  - 2017-05-10-13-14-16.public-release.db3
  starting_time:
    nanoseconds_since_epoch: 1494414857109509971
  storage_identifier: sqlite3
  topics_with_message_count:
  - message_count: 31110
    topic_metadata:
      name: /imu
      offered_qos_profiles: ''
      serialization_format: cdr
      type: sensor_msgs/msg/Imu
  - message_count: 15555
    topic_metadata:
      name: /wheel_rpm
      offered_qos_profiles: ''
      serialization_format: cdr
      type: geometry_msgs/msg/QuaternionStamped
  - message_count: 117197
    topic_metadata:
      name: /velodyne_points
      offered_qos_profiles: ''
      serialization_format: cdr
      type: sensor_msgs/msg/PointCloud2
  - message_count: 38885
    topic_metadata:
      name: /optical_speed_sensor
      offered_qos_profiles: ''
      serialization_format: cdr
      type: geometry_msgs/msg/TwistStamped
  - message_count: 1555
    topic_metadata:
      name: /gps
      offered_qos_profiles: ''
      serialization_format: cdr
      type: sensor_msgs/msg/NavSatFix
  version: 4
